/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BusinessIncomeTaxUpdateManyWithoutUsersInput } from "./BusinessIncomeTaxUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GstUpdateManyWithoutUsersInput } from "./GstUpdateManyWithoutUsersInput";
import { IndividualIncomeTaxUpdateManyWithoutUsersInput } from "./IndividualIncomeTaxUpdateManyWithoutUsersInput";
import { LegalComplianceUpdateManyWithoutUsersInput } from "./LegalComplianceUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TdsUpdateManyWithoutUsersInput } from "./TdsUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BusinessIncomeTaxUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BusinessIncomeTaxUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BusinessIncomeTaxUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  businessIncomeTaxes?: BusinessIncomeTaxUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => GstUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => GstUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => GstUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  gsts?: GstUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => IndividualIncomeTaxUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => IndividualIncomeTaxUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => IndividualIncomeTaxUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  individualIncomeTaxes?: IndividualIncomeTaxUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LegalComplianceUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LegalComplianceUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LegalComplianceUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  legalCompliances?: LegalComplianceUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TdsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TdsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TdsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tdsItems?: TdsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
